(import (vanity core) (vanity plot))
(define myplot (make-plot 600 600))
(define xs #f32(1 2 3 4 5))
(define ys #f32(1 4 9 16 25))
(plot-line-strip myplot xs ys)
(plot-color myplot 1 0 0)
(plot-points myplot xs ys)
(let loop ()
  (if (plot-alive? myplot) (loop)))
