(define-library (vanity plot)
  (export make-plot close-plot plot-alive? plot-color plot-point plot-points plot-line plot-line-strip plot-continuous plot-clear plot-begin-frame plot-end-frame)
  (import (vanity core))
  (##foreign.import "C" "plot.h")

  (define (make-plot x y)
    (let ((plot (make_plot x y)))
      (##vcore.set-finalizer! plot (lambda (plot) (close_plot plot)))
      plot))
  (define plot-alive? plot_alive)
  (define (close-plot plot)
    (##vcore.finalize! plot))
  (define (plot-point plot x y)
    (plot_point plot x y))
  (define plot-color plot_color)
  (define (plot-points plot xs ys)
    (let ((lena (f32vector-length xs))
          (lenb (f32vector-length ys)))
      (if (not (= lena lenb))
          (error "plot-points: xs and ys are not equal length"))
      (plot_points plot lena xs ys)))
  (define (plot-line plot x1 y1 x2 y2)
    (plot_line plot x1 y1 x2 y2))
  (define (plot-line-strip plot xs ys)
    (let ((lena (f32vector-length xs))
          (lenb (f32vector-length ys)))
      (if (not (= lena lenb))
          (error "plot-points: xs and ys are not equal length"))
      (plot_line_strip plot lena xs ys)))
  (define plot-continuous plot-continuous)
  (define plot-clear plot_clear)
  (define plot-begin-frame plot_begin_frame)
  (define plot-end-frame plot_end_frame))
